import '@/styles/reset.css';
import '@/styles/global.css';
import type { AppProps } from 'next/app';
import Layout from '@/components/template/layout/Layout';
import Root from '@/components/template/root/Root';
import React from 'react';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Root>
      <Layout>
        <Head>
          <title>{'강의 등록 플랫폼 - 다모'}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </Root>
  );
}
