import Head from 'next/head';
import { ArticleMain } from '@/styles/pages/Main.styles';
import { useApp } from '@/components/providers/serviceApp/ServiceApp';

export default function Home() {
  const { headTitle } = useApp();

  return (
    <ArticleMain>
      <Head>
        <title>{headTitle || ''}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>메인 페이지</div>
    </ArticleMain>
  );
}
