import Head from 'next/head';
import { Inter } from 'next/font/google';
export default function Home() {
  return (
    <>
      <Head>
        <title>{'강의 등록 플랫폼 - 다모'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>메인 페이지</div>
    </>
  );
}
